version: '3.8'
services:
  db:
    build:
      context: ./
      dockerfile: Dockerfile-mysql
    #    Uncomment if you want to override the password from Dockerfile-spring-mysql
    #    environment:
    #      MYSQL_ROOT_PASSWORD: replacement_for_passw0rd
    ports:
      - "3306:3306"
    networks:
      - mysqlnet
  db-web-client:
    image: adminer
    ports:
      - 8081:8080
    networks:
      - mysqlnet
  spring-app:
    build:
      context: ./
      dockerfile: Dockerfile-spring
    environment:
      # delete dbseeder profile if you don't want to use DBSeeder when Spring Boot starts its context
      SPRING_PROFILE: mysql, dbseeder
      DB_HOST: db
    ports:
      - "8080:8080"
    networks:
      - mysqlnet

networks:
  mysqlnet: